nodeLinker: node-modules

plugins:
  # Runs `yarn dedupe` after every install (if needed)
  # Source: https://github.com/ambar/yarn-plugin-dedupe-on-install
  - path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/main/index.js"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
